routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function(){
    Route::resource('projects','IdeasController');
    Route::get('my-projects', "IdeasController@projectsUser")->name('projects.myprojects');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=["name","description"];
}

app/Evaluation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Evaluation extends Model
{
    protected $fillable = [];
}

app/Idea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Idea extends Model
{
    protected $fillable = ['name', 'description', 'status', 'project_type', 'private'];
    protected $hidden = ['id'];

    public function users()
    {
        return $this->belongsToMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function ideas()
    {
        return $this->belongsToMany('App\Idea');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EvaluationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class EvaluationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/IdeasController.php
<?php

namespace App\Http\Controllers;

use App\Idea;
use Illuminate\Http\Request;
use App\User;

class IdeasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|min:4',
            'description'=>'required',
            'status'=>'required',
            'type'=>'required',
            'private'=>'required',
            'user_id'=>'required'
        ]);
        $data = $request->except(['user_id','_token']);

        $user = User::find($request->user_id);
        $store = Idea::create($data);
        //dd($store->id);
        $user->ideas()->attach($store->id,['level'=>1]);
        return redirect()->back()->with(['status'=>'Cadastrado com sucesso']);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function projectsUser()
    {
        return view ('projects.list');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="align-center">
            <img src="img/LogoTCCSolution.PNG" alt="">
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="align-center">
                <label>Busque por:</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo_busca" id="titulo" value="titulo" checked>
                    <label class="form-check-label" for="titulo">Título</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo_busca" id="categoria" value="categoria">
                    <label class="form-check-label" for="categoria">Categoria</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="tipo_busca" id="tipoprojeto" value="tipoprojeto">
                    <label class="form-check-label" for="tipoprojeto">Tipo Projeto</label>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="form-row">
                <div class="col-sm-12 my-1">
                    <input type="text" class="form-control" id="pesquisar" placeholder="Pesquisar" autofocus>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-green navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                        <li>
                            <a href="{{ route('projects.myprojects') }}" class="nav-link">Meus Projetos</a>
                        </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">Registrar</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="{{ route('projects.create') }}" class="dropdown-item">Novo Projeto</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>

                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <h3>Novo Projeto</h3>
        </div>
        @if ($errors->any())
            <div class="row justify-content-center">
                <div class="col-4 alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @elseif(session('status'))
            <div class="row justify-content-center">
                <div class="col-4 alert alert-success">
                    {{ session('status') }}
                </div>
            </div>
        @endif
        <div class="row justify-content-center">
            <form class="col-4" method="POST" action="{{ route('projects.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Nome para sua ideia" autocomplete="off" value="{{ old('name') }}">
                    <small id="nomeHelp" class="form-text text-muted">Mínimo de 4 caracteres.</small>
                </div>
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" id="description" name="description" placeholder="Descreva sua ideia">{{ old('description') }}</textarea>
                    <small id="nomeHelp" class="form-text text-muted">Mínimo de 10 caracteres.</small>
                </div>
                <div class="form-group">
                    <label for="status">Status</label>
                    <select name="status" id="status" class="form-control">
                        <option value="nao iniciado" {{ old('status') === 'nao iniciado' ? 'selected' : ''  }}>Não iniciado</option>
                        <option value="andamento" {{ old('status') === 'andamento' ? 'selected' : ''  }}>Andamento</option>
                        <option value="concluido" {{ old('status') === 'concluido' ? 'selected' : ''  }}>Concluído</option>
                        <option value="pausado" {{ old('status') === 'pausado' ? 'selected' : ''  }}>Pausado</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="type">Tipo</label>
                    <select name="type" id="type" class="form-control">
                        <option value="TCC" {{ old('type') === 'TCC' ? 'selected' : ''  }}>TCC</option>
                        <option value="ARTIGO" {{ old('type') === 'ARTIGO' ? 'selected' : ''  }}>Artigo</option>
                        <option value="PROJETO CIENTIFICO" {{ old('type') === 'PROJETO CIENTIFICO' ? 'selected' : ''  }}>Projeto Cientifico</option>
                        <option value="PESQUISA ACADEMICA" {{ old('type') === 'PESQUISA ACADEMICA' ? 'selected' : ''  }}>Pesquisa acadêmica</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="private">Visibilidade</label>
                    <select name="private" id="private" class="form-control">
                        <option value="PUBLIC" {{ old('private') === 'PUBLIC' ? 'selected' : ''  }}>Público</option>
                        <option value="PRIVATE" {{ old('private') === 'PRIVATE' ? 'selected' : ''  }}>Privado</option>
                    </select>
                </div>
                <input type="hidden" name="user_id" value="{{ auth()->user()->getAuthIdentifier() }}">
                <button type="submit" class="btn btn-primary btn-block">Criar</button>
            </form>
        </div>
    </div>
@endsection

resources/views/projects/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h3 class="border-bottom pb-2 mb-0">Meus Projetos</h3>
            <div class="container pt-3 border-bottom border-gray">
                <img src="" alt="">
                <a href="#" class="media-body pb-3 mb-0">Testando</a>
                <div class="clearfix"></div>
                <small class="small">Mussum Ipsum, cacilds vidis litro abertis. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Casamenti... </small>
                <div class="clearfix"></div>
                <button class="btn btn-sm btn-danger mt-1 mb-3">Apagar</button>
            </div>
            <div class="container pt-3 border-bottom border-gray">
                <img src="" alt="">
                <a href="#" class="media-body pb-3 mb-0">Testando</a>
                <div class="clearfix"></div>
                <small class="small">Mussum Ipsum, cacilds vidis litro abertis. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Casamenti... </small>
                <div class="clearfix"></div>
                <button class="btn btn-sm btn-danger mt-1 mb-3">Apagar</button>
            </div>
        </div>
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h3 class="border-bottom pb-2 mb-0">Projetos em que participo</h3>
            <div class="container pt-3 border-bottom border-gray">
                <img src="" alt="">
                <a href="#" class="media-body pb-3 mb-0">Testando</a>
                <p class="small">@user</p>
                <div class="clearfix"></div>
                <small class="small">Mussum Ipsum, cacilds vidis litro abertis. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Casamenti... </small>
            </div>
            <div class="container pt-3 border-bottom border-gray">
                <img src="" alt="">
                <a href="#" class="media-body pb-3 mb-0">Testando</a>
                <p class="small">@user</p>
                <div class="clearfix"></div>
                <small class="small">Mussum Ipsum, cacilds vidis litro abertis. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Casamenti... </small>
            </div>
        </div>
    </div>
@endsection